version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgresqlservice
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: devopscourse
      POSTGRES_USER: devopscourseuser
      POSTGRES_PASSWORD: devopscoursepassword
    volumes:
      - /Users/erekle.magradze/CodeArea/containervolumes/pgdata:/var/lib/postgresql/data
      - './init.sql:/docker-entrypoint-initdb.d/init-script.sql'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4service
    depends_on:
      - db
    restart: always
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: devops@gmail.com
      PGADMIN_DEFAULT_PASSWORD: somepasswordhere
    volumes:
      - /Users/erekle.magradze/CodeArea/containervolumes/pgadmin:/var/lib/pgadmin
